### PR TITLE
add pretty-printf, etc.

### PR DESCRIPTION
**Pull request by AlexKnauth**
This adds `pretty-printf`, `pretty-fprintf`, and `pretty-eprintf`.

### CODE REVIEW

**Comment by stamourv** [comment]
Let's not add more stuff to the `unstable` packages.
Those sound like good additions for `racket/pretty`, so please submit a PR there.

**Comment by AlexKnauth** [comment]
Right now, they aren't exactly like the non-pretty versions because they each append one extra newline at the end. That's why I thought they should be unstable. If there's a way to fix that, great, but otherwise they wouldn't be something we want marked as stable.

**Comment by stamourv** [comment]
To fix, could you print to a string, then chop off the last newline?

**Comment by AlexKnauth** [comment]
Right now stuff like `(pretty-printf "~a = ~v" 'img (circle 20 "outline" "red"))` works fine. If I print to a string and chop off the last newline, images and other non-text values won't print properly.

**Comment by stamourv** [comment]
I see.
If you move those to `racket/pretty`, though, you should be able to add the hooks needed to get rid of the newline in the lower-level pretty-prin function.

**Comment by AlexKnauth** [comment]
Would it make sense to define a version of `pretty-print` that doesn't print the extra newline?

**Comment by rfindler** [comment]
FWIW, DrRacket does some fancy dance for these newlines, too.

You can, instead of a string port, use another kind of port and copy values out of it (except that last newline), if you want. Probably better to add a parameter and adjust the pretty-printing library, tho. Seems simpler and without lots of pain.

**Pull request closed without merging**
